server:
  port: 9988
  #全局配置gzip压缩  服务消费者到服务提供者开启，浏览器到消费者也开启
  compression:
    enabled: true
    mime-types: text/xml,application/xml,application/json,text/plain

spring:
  application:
    name: service-consumer

eureka:
#  instance:
#    prefer-ip-address: true   #显示IP
#    instance-id: ${spring.cloud.client.ip-address}:${server.port} #以这种形式显示
  client:
    register-with-eureka: false
    registry-fetch-interval-seconds: 10 #到注册中心拉去注册信息的时间，默认30s
    #    fetch-registry: false
    service-url:
      defaultZone: http://root:123456@localhost:8761/eureka/,http://root:123456@localhost:8762/eureka/,

#指定服务使用何种负载均衡策略
service-provider:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
    #指定具体服务提供者列表
    listOfServers: http://localhost:7070,http://localhost:7071

feign:
  httpclient:
    enabled: true
  client:
    config:
      service-provider: #指定服务名称
        loggerLevel: FULL

