server:
  port: 9090

spring:
  application:
    name: service-consumer

eureka:
#  instance:
#    prefer-ip-address: true   #显示IP
#    instance-id: ${spring.cloud.client.ip-address}:${server.port} #以这种形式显示
  client:
    register-with-eureka: false
    registry-fetch-interval-seconds: 10 #到注册中心拉去注册信息的时间，默认30s
    #    fetch-registry: false
    service-url:
      defaultZone: http://root:123456@localhost:8761/eureka/,http://root:123456@localhost:8762/eureka/,

#指定服务使用何种负载均衡策略
service-provider:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
    #指定具体服务提供者列表
    listOfServers: http://localhost:7070,http://localhost:7071

#局部配置Feign gzip压缩  服务消费者到服务提供者开启，浏览器到消费者是没有开启的
feign:
  compression:
    request:
      mime-types: text/xml,application/xml,application/json #配置压缩支持的MIME类型
      min-request-size: 512                                 #配置压缩数据大小的最小阈值 默认2048
      enabled: true                                         #开启
    response:
      enabled: true                                         #响应时也开启

